Update azure-storage.json: Fix error TS2428 in tsc
There is a reported error with tsc 2.0.3+.
It is "error TS2428" and it is because an interface and a class named exactly the same.